apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: scaligator-cpu-rules
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: scaligator.rules
      rules:
        - alert: HighCPUUsage
          expr: |
            rate(container_cpu_usage_seconds_total{namespace=~"default|scaling|dev"}[2m]) > 0.7
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Pod {{ $labels.pod }} in {{ $labels.namespace }} using > 70% CPU"
            cpu: "{{ $value }}"
